apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  namespace: udagram
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels: 
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: rowlandekemezie/udagram-api-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST
              value: "udagram-db.cy1a8vcfhlgm.us-west-2.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"
            - name: AWS_BUCKET
              value: "udagram-project-4-dev"
            - name: AWS_REGION
              value: "us-west-2"
            - name: AWS_PROFILE
              value: "default"
            - name: JWT_SECRET
              value: "test"
            - name: URL
              value: "http://localhost:8100"
      restartPolicy: Always
